config/routes.rb
Rails.application.routes.draw do
    devise_for :customers, controllers: {
    registrations: "public/registrations",#登録
    sessions: 'public/sessions'#ログイン
  }

  devise_for :admins, controllers: {
    sessions: "admin/sessions"#ログイン
  }

  namespace :public do
    get 'items/index'
    get 'items/show'
  end
  namespace :public do
    get 'homes/top'
    get 'homes/about'
  end
  scope module: :public do
    root controller: :homes, action: :top
    get :about, controller: :homes, action: :about
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    # delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    resources :orders, only: %i(new create index show) do
      collection do
        post :confirm
        get :complete
      end
    end
    #post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    #get 'orders/complete' => 'orders#complete', as: 'complete'
  end

  namespace :admin do
    root "homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name , presence: true
  validates :introduction , presence: true
  validates :price , presence: true

  has_many :cart_items, dependent: :destroy

  has_one_attached :profile_image#画像用のカラム名

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed

  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items =Item.all
  end

  def new
    @item =Item.new


  end

  def create
    @item =Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def show
    @item =Item.find(params[:id])
  end

  def edit
    @item =Item.find(params[:id])
  end

  def update
    @item =Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)

  end

private
  def item_params
    params.require(:item).permit(:name, :introduction, :price, :profile_image)
  end


end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>

<%= form_with model: @item, url: admin_item_path(@item.id) do |f| %>
<br>

  <table>
  <tr>
  <h4>商品画像</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>
  </tr>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_field :introduction %>
  <h4>税抜価格</h4>
  <%= f.text_field :price %>円
  </table>
  <br>
  <%= f.submit '変更を保存', class: "btn btn-success" %>
<% end %>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>

  <%= link_to new_admin_item_path, class: "btn btn-light" do%>
  +
  <%end%>
<br>
<table border="1">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
    </tr>
<% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item.id), class: "btn btn-light" %></td>
      <td><%= item.price %></td>
    </tr>
<% end %>
</table>

app/views/admin/items/new.html.erb
<h4>商品新規登録</h4>
<%= form_with model: @item, url: admin_items_path do |f| %>
<br>
  <div>
  <tr>
  <h4>商品画像</h4>
  <%= f.file_field :profile_image, accept: "image/*" %>
  </tr>
  <h4>商品名</h4>
  <%= f.text_field :name %>
  <h4>商品説明</h4>
  <%= f.text_field :introduction %>
  <h4>税抜価格</h4>
  <%= f.text_field :price %>円

  <br>
  <br>
  <%= f.submit '新規登録', class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/items/show.html.erb
<h4>商品詳細</h4>

  <%= image_tag @item.profile_image %>

  <table>
    <tr>
      <td>商品名</td>
      <td><%= @item.name %></td>
    </tr>
    <tr>
      <td>商品説明</td>
      <td><%= @item.introduction %></td>
    </tr>
    <tr>
      <td>税込価格(税抜価格)</td>
      <td><%= (@item.price*1.1).floor %>(<%= @item.price %>)円</td>
    </tr>
  </table>
<br>

<%=link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>